# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vector_model.proto\x12\x0cvector_model\"\x1d\n\rEncodeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x9f\x01\n\x0e\x45ncodeResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x38\n\x06sparse\x18\x03 \x03(\x0b\x32(.vector_model.EncodeResponse.SparseEntry\x1a-\n\x0bSparseEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"#\n\x12\x42\x61tchEncodeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"B\n\x13\x42\x61tchEncodeResponse\x12+\n\nembeddings\x18\x01 \x03(\x0b\x32\x17.vector_model.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x14\n\x12HealthCheckRequest\"]\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06socket\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x11\n\tdimension\x18\x04 \x01(\x05\"1\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\" \n\x0eRerankResponse\x12\x0e\n\x06scores\x18\x01 \x03(\x02\x32\xc6\x02\n\x12VectorModelService\x12\x43\n\x06\x45ncode\x12\x1b.vector_model.EncodeRequest\x1a\x1c.vector_model.EncodeResponse\x12R\n\x0b\x42\x61tchEncode\x12 .vector_model.BatchEncodeRequest\x1a!.vector_model.BatchEncodeResponse\x12R\n\x0bHealthCheck\x12 .vector_model.HealthCheckRequest\x1a!.vector_model.HealthCheckResponse\x12\x43\n\x06Rerank\x12\x1b.vector_model.RerankRequest\x1a\x1c.vector_model.RerankResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODERESPONSE_SPARSEENTRY']._loaded_options = None
  _globals['_ENCODERESPONSE_SPARSEENTRY']._serialized_options = b'8\001'
  _globals['_ENCODEREQUEST']._serialized_start=36
  _globals['_ENCODEREQUEST']._serialized_end=65
  _globals['_ENCODERESPONSE']._serialized_start=68
  _globals['_ENCODERESPONSE']._serialized_end=227
  _globals['_ENCODERESPONSE_SPARSEENTRY']._serialized_start=182
  _globals['_ENCODERESPONSE_SPARSEENTRY']._serialized_end=227
  _globals['_BATCHENCODEREQUEST']._serialized_start=229
  _globals['_BATCHENCODEREQUEST']._serialized_end=264
  _globals['_BATCHENCODERESPONSE']._serialized_start=266
  _globals['_BATCHENCODERESPONSE']._serialized_end=332
  _globals['_EMBEDDING']._serialized_start=334
  _globals['_EMBEDDING']._serialized_end=361
  _globals['_HEALTHCHECKREQUEST']._serialized_start=363
  _globals['_HEALTHCHECKREQUEST']._serialized_end=383
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=385
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=478
  _globals['_RERANKREQUEST']._serialized_start=480
  _globals['_RERANKREQUEST']._serialized_end=529
  _globals['_RERANKRESPONSE']._serialized_start=531
  _globals['_RERANKRESPONSE']._serialized_end=563
  _globals['_VECTORMODELSERVICE']._serialized_start=566
  _globals['_VECTORMODELSERVICE']._serialized_end=892
# @@protoc_insertion_point(module_scope)
