# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vector_model.proto\x12\x0cvector_model\"\x1d\n\rEncodeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x0e\x45ncodeResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\"#\n\x12\x42\x61tchEncodeRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"B\n\x13\x42\x61tchEncodeResponse\x12+\n\nembeddings\x18\x01 \x03(\x0b\x32\x17.vector_model.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x14\n\x12HealthCheckRequest\"]\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06socket\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x11\n\tdimension\x18\x04 \x01(\x05\x32\x81\x02\n\x12VectorModelService\x12\x43\n\x06\x45ncode\x12\x1b.vector_model.EncodeRequest\x1a\x1c.vector_model.EncodeResponse\x12R\n\x0b\x42\x61tchEncode\x12 .vector_model.BatchEncodeRequest\x1a!.vector_model.BatchEncodeResponse\x12R\n\x0bHealthCheck\x12 .vector_model.HealthCheckRequest\x1a!.vector_model.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=36
  _globals['_ENCODEREQUEST']._serialized_end=65
  _globals['_ENCODERESPONSE']._serialized_start=67
  _globals['_ENCODERESPONSE']._serialized_end=121
  _globals['_BATCHENCODEREQUEST']._serialized_start=123
  _globals['_BATCHENCODEREQUEST']._serialized_end=158
  _globals['_BATCHENCODERESPONSE']._serialized_start=160
  _globals['_BATCHENCODERESPONSE']._serialized_end=226
  _globals['_EMBEDDING']._serialized_start=228
  _globals['_EMBEDDING']._serialized_end=255
  _globals['_HEALTHCHECKREQUEST']._serialized_start=257
  _globals['_HEALTHCHECKREQUEST']._serialized_end=277
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=279
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=372
  _globals['_VECTORMODELSERVICE']._serialized_start=375
  _globals['_VECTORMODELSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
