// Copyright (c) 2026 qyiun666
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Stage: L2 Merge-Compress — apply pre-computed LLM groups to the storage layer.

use crate::dream::llm::L2Group;
use crate::encoder::Encoder;
use crate::index::l2_meta::L2MetaIndex;
use crate::index::sparse::SparseIndex;
use crate::layers::context::TopicSlot;
use crate::query::types::MergeCompressResult;
use crate::storage::record::REC_L2_TOPIC;
use crate::storage::StorageEngine;
use crate::util::get_current_timestamp;
use crate::MemHopError;

/// Apply pre-computed L2 groups from the consolidated LLM call.
///
/// Each group has its merged title + summary already generated by the LLM.
/// This function only handles writing the parent node, sinking children,
/// and updating indices — no additional LLM calls.
///
/// Returns (groups_detected, nodes_merged, parent_nodes_created, nodes_sunk, nodes_removed).
pub fn apply_precomputed_groups(
    groups: &[L2Group],
    engine: &mut StorageEngine,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    encoder: Option<&(dyn Encoder + Send + Sync)>,
) -> Result<(u32, u32, u32, u32, u32), MemHopError> {
    let mut groups_detected = 0u32;
    let mut nodes_merged = 0u32;
    let mut parents_created = 0u32;
    let mut nodes_sunk = 0u32;
    let mut nodes_removed = 0u32;

    for group in groups {
        if group.node_hashes.len() < 2 {
            continue;
        }
        groups_detected += 1;
        nodes_merged += group.node_hashes.len() as u32;

        let now_ms = get_current_timestamp();
        let scene_id = group.scene_id;
        let parent_id_hash =
            crate::util::hash_id(&format!("merged_parent_{}_{}", scene_id, now_ms));

        // Centroid vector encoding (v2: centroid_page_ref is not used, set to 0)
        let _centroid_bytes: Option<Vec<u8>> = if let Some(enc) = encoder {
            match enc.encode(&group.merged_summary) {
                Ok(output) => {
                    let v_bytes: Vec<u8> =
                        output.dense.iter().flat_map(|v| v.to_ne_bytes()).collect();
                    Some(v_bytes)
                }
                Err(e) => {
                    tracing::warn!("Centroid encode failed: {}", e);
                    None
                }
            }
        } else {
            None
        };

        let parent_node = TopicSlot {
            id: parent_id_hash,
            scene_id,
            parent_id: None,
            children_ids: group.node_hashes.clone(),
            depth: 1,
            user_keywords: vec![],
            user_timestamp: now_ms,
            user_l4_refs: vec![],
            user_l3_refs: vec![],
            agent_keywords: vec![],
            agent_timestamp: now_ms,
            agent_l4_refs: vec![],
            agent_l3_refs: vec![],
            fused_keywords: vec![group.merged_title.clone()],
            fused_summary: Some(group.merged_summary.clone()),
            centroid_page_ref: 0,
            created_at: now_ms,
            updated_at: now_ms,
            version: 3,
        };

        // Persist parent via engine
        let parent_data = bincode::serialize(&parent_node)
            .map_err(|e| MemHopError::Serialization(e.to_string()))?;
        engine.write_record(REC_L2_TOPIC, parent_id_hash, &parent_data)?;

        let index_terms =
            crate::index::sparse::tokenize(parent_node.fused_summary.as_deref().unwrap_or(""));
        sparse_index.add_document(
            parent_id_hash,
            index_terms.clone(),
            index_terms.len() as u32,
        );
        parents_created += 1;

        // Sink each child
        for &child_id in &group.node_hashes {
            let mut result = MergeCompressResult {
                groups_detected: 0,
                nodes_merged: 0,
                parent_nodes_created: 0,
                nodes_sunk: 0,
                nodes_removed: 0,
            };
            sink_subtree(
                child_id,
                parent_id_hash,
                engine,
                sparse_index,
                l2_meta,
                &mut result,
            )?;
            nodes_sunk += result.nodes_sunk;
            nodes_removed += result.nodes_removed;
        }

        l2_meta.update_from_context(&parent_node);
    }

    Ok((
        groups_detected,
        nodes_merged,
        parents_created,
        nodes_sunk,
        nodes_removed,
    ))
}

/// Sink a node's depth by 1 and update its parent.
///
/// If the new depth ≥ 4 the node and its entire subtree are deleted.
/// Otherwise the node is saved and its own children are sunk recursively.
fn sink_subtree(
    id_hash: u64,
    new_parent_id: u64,
    engine: &mut StorageEngine,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    result: &mut MergeCompressResult,
) -> Result<(), MemHopError> {
    let (_, data) = match engine.read_record(id_hash)? {
        Some(v) => v,
        None => return Ok(()),
    };
    let mut ctx: TopicSlot = match bincode::deserialize(data) {
        Ok(c) => c,
        Err(_) => return Ok(()),
    };

    ctx.depth += 1;
    let new_depth = ctx.depth;
    ctx.parent_id = Some(new_parent_id);
    ctx.updated_at = get_current_timestamp();

    if new_depth >= 4 {
        // Delete this node and all descendants
        return free_node_and_descendants(id_hash, engine, sparse_index, l2_meta, result);
    }

    // Save updated node
    let ctx_data =
        bincode::serialize(&ctx).map_err(|e| MemHopError::Serialization(e.to_string()))?;
    engine.write_record(REC_L2_TOPIC, id_hash, &ctx_data)?;

    // Update in-memory L2 metadata index
    l2_meta.update_from_context(&ctx);

    result.nodes_sunk += 1;

    // Recursively sink children
    let child_ids = ctx.children_ids.clone();
    for &child_id in &child_ids {
        sink_subtree(child_id, id_hash, engine, sparse_index, l2_meta, result)?;
    }

    // After sinking children, some may have been deleted (depth >= 4).
    // Clean up children_ids to remove references to deleted children.
    let original_len = ctx.children_ids.len();
    ctx.children_ids.retain(|&cid| engine.contains(cid));
    if ctx.children_ids.len() < original_len {
        // Re-serialize and write updated node with cleaned children_ids
        let ctx_data =
            bincode::serialize(&ctx).map_err(|e| MemHopError::Serialization(e.to_string()))?;
        engine.write_record(REC_L2_TOPIC, id_hash, &ctx_data)?;
        l2_meta.update_from_context(&ctx);
    }

    Ok(())
}

/// Recursively delete a node and all its descendants.
///
/// Removes the node from the sparse index, L2 meta index, and deletes the record.
fn free_node_and_descendants(
    id_hash: u64,
    engine: &mut StorageEngine,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    result: &mut MergeCompressResult,
) -> Result<(), MemHopError> {
    // Load node to traverse children
    let ctx = {
        let (_, data) = match engine.read_record(id_hash)? {
            Some(v) => v,
            None => return Ok(()),
        };
        match bincode::deserialize::<TopicSlot>(data) {
            Ok(c) => c,
            Err(_) => return Ok(()),
        }
    };

    // Recursively free children first (post-order traversal)
    let child_ids = ctx.children_ids.clone();
    for &child_id in &child_ids {
        free_node_and_descendants(child_id, engine, sparse_index, l2_meta, result)?;
    }

    // Remove from indices
    sparse_index.remove_document(id_hash);
    l2_meta.remove(id_hash);

    // Delete the record
    engine.delete_record(id_hash)?;

    result.nodes_removed += 1;

    Ok(())
}
