// Copyright (c) 2026 qyiun666
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Stage: L2 Merge-Compress — apply pre-computed LLM groups to the storage layer.

use crate::dream::llm::L2Group;
use crate::encoder::Encoder;
use crate::file::free_list::free_page;
use crate::file::header::FileHeader;
use crate::file::page::{allocate_page, encode_page_ref, write_page_data};
use crate::index::btree::BTreeIndex;
use crate::index::l2_meta::L2MetaIndex;
use crate::index::sparse::SparseIndex;
use crate::layers::context::ContextSlot;
use crate::query::types::MergeCompressResult;
use crate::util::{get_current_timestamp, PageType, PAGE_SIZE};
use crate::MemHopError;
use memmap2::MmapMut;
use std::fs::File;

/// Apply pre-computed L2 groups from the consolidated LLM call.
///
/// Each group has its merged title + summary already generated by the LLM.
/// This function only handles writing the parent node, sinking children,
/// and updating indices — no additional LLM calls.
///
/// Returns (groups_detected, nodes_merged, parent_nodes_created, nodes_sunk, nodes_removed).
#[allow(clippy::too_many_arguments)]
pub fn apply_precomputed_groups(
    groups: &[L2Group],
    mmap: &mut MmapMut,
    header: &mut FileHeader,
    btree: &mut BTreeIndex,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    encoder: Option<&(dyn Encoder + Send + Sync)>,
    file: &mut File,
) -> Result<(u32, u32, u32, u32, u32), MemHopError> {
    let mut groups_detected = 0u32;
    let mut nodes_merged = 0u32;
    let mut parents_created = 0u32;
    let mut nodes_sunk = 0u32;
    let mut nodes_removed = 0u32;

    for group in groups {
        if group.node_hashes.len() < 2 {
            continue;
        }
        groups_detected += 1;
        nodes_merged += group.node_hashes.len() as u32;

        let now_ms = get_current_timestamp();
        let scene_id = group.scene_id;
        let parent_id_hash =
            crate::util::hash_id(&format!("merged_parent_{}_{}", scene_id, now_ms));

        // Compute centroid from merged summary
        let centroid_page_ref = if let Some(enc) = encoder {
            match enc.encode(&group.merged_summary) {
                Ok(output) => {
                    let v_page_id =
                        allocate_page(mmap, header, PageType::VectorMatrix, 2, 0, file)?;
                    let v_offset = crate::shared::slot_io::slot_offset(v_page_id);
                    let v_bytes: Vec<u8> =
                        output.dense.iter().flat_map(|v| v.to_ne_bytes()).collect();
                    if v_offset + v_bytes.len() <= mmap.len() {
                        mmap[v_offset..v_offset + v_bytes.len()].copy_from_slice(&v_bytes);
                        encode_page_ref(v_page_id, 0)
                    } else {
                        let _ = free_page(mmap, header, v_page_id);
                        0
                    }
                }
                Err(e) => {
                    tracing::warn!("Centroid encode failed: {}", e);
                    0
                }
            }
        } else {
            0
        };

        let parent_node = ContextSlot {
            id: parent_id_hash,
            scene_id,
            parent_id: None,
            children_ids: group.node_hashes.clone(),
            depth: 1,
            user_keywords: vec![],
            user_timestamp: now_ms,
            user_l4_refs: vec![],
            user_l3_refs: vec![],
            agent_keywords: vec![],
            agent_timestamp: now_ms,
            agent_l4_refs: vec![],
            agent_l3_refs: vec![],
            fused_keywords: vec![group.merged_title.clone()],
            fused_summary: Some(group.merged_summary.clone()),
            centroid_page_ref,
            created_at: now_ms,
            updated_at: now_ms,
            version: 3,
        };

        // Persist parent
        let parent_page_id = allocate_page(mmap, header, PageType::Context, 2, 0, file)?;
        let parent_data = parent_node
            .serialize()
            .map_err(|e| MemHopError::Serialization(e.to_string()))?;
        write_page_data(mmap, parent_page_id, &parent_data)?;
        btree.insert(parent_id_hash, encode_page_ref(parent_page_id, 0));
        let index_terms =
            crate::index::sparse::tokenize(parent_node.fused_summary.as_deref().unwrap_or(""));
        sparse_index.add_document(
            parent_id_hash,
            index_terms.clone(),
            index_terms.len() as u32,
        );
        parents_created += 1;

        // Sink each child
        for &child_id in &group.node_hashes {
            let mut result = MergeCompressResult {
                groups_detected: 0,
                nodes_merged: 0,
                parent_nodes_created: 0,
                nodes_sunk: 0,
                nodes_removed: 0,
            };
            sink_subtree(
                child_id,
                parent_id_hash,
                mmap,
                header,
                btree,
                sparse_index,
                l2_meta,
                file,
                &mut result,
            )?;
            nodes_sunk += result.nodes_sunk;
            nodes_removed += result.nodes_removed;
        }

        l2_meta.update_from_context(&parent_node);
    }

    Ok((
        groups_detected,
        nodes_merged,
        parents_created,
        nodes_sunk,
        nodes_removed,
    ))
}

/// Sink a node's depth by 1 and update its parent.
///
/// If the new depth ≥ 4 the node and its entire subtree are deleted.
/// Otherwise the node is saved and its own children are sunk recursively.
#[allow(clippy::too_many_arguments)]
fn sink_subtree(
    id_hash: u64,
    new_parent_id: u64,
    mmap: &mut MmapMut,
    header: &mut FileHeader,
    btree: &mut BTreeIndex,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    file: &mut File,
    result: &mut MergeCompressResult,
) -> Result<(), MemHopError> {
    let page_ref = match btree.search(id_hash) {
        Some(pr) => pr,
        None => return Ok(()),
    };
    let page_id = crate::shared::slot_io::decode_page_id(page_ref);
    let slot_data = match crate::shared::slot_io::get_slot_data(&mmap[..], page_ref) {
        Some(d) => d,
        None => return Ok(()),
    };
    let mut ctx = match ContextSlot::deserialize(slot_data) {
        Ok(c) => c,
        Err(_) => return Ok(()),
    };

    ctx.depth += 1;
    let new_depth = ctx.depth;
    ctx.parent_id = Some(new_parent_id);
    ctx.updated_at = get_current_timestamp();

    if new_depth >= 4 {
        // Delete this node and all descendants
        return free_node_and_descendants(
            id_hash,
            mmap,
            header,
            btree,
            sparse_index,
            l2_meta,
            file,
            result,
        );
    }

    // Save updated node
    let data = ctx
        .serialize()
        .map_err(|e| MemHopError::Serialization(e.to_string()))?;
    write_page_data(mmap, page_id, &data)?;

    // Update in-memory L2 metadata index
    l2_meta.update_from_context(&ctx);

    result.nodes_sunk += 1;

    // Recursively sink children
    let child_ids = ctx.children_ids.clone();
    for &child_id in &child_ids {
        sink_subtree(
            child_id,
            id_hash,
            mmap,
            header,
            btree,
            sparse_index,
            l2_meta,
            file,
            result,
        )?;
    }

    // After sinking children, some may have been deleted (depth >= 4).
    // Clean up children_ids to remove references to deleted children.
    let original_len = ctx.children_ids.len();
    ctx.children_ids.retain(|&cid| btree.search(cid).is_some());
    if ctx.children_ids.len() < original_len {
        // Re-serialize and write updated node with cleaned children_ids
        let data = ctx
            .serialize()
            .map_err(|e| MemHopError::Serialization(e.to_string()))?;
        write_page_data(mmap, page_id, &data)?;
        l2_meta.update_from_context(&ctx);
    }

    Ok(())
}

/// Recursively delete a node and all its descendants.
///
/// Removes the node from the B-tree, sparse index, L2 meta index, frees the
/// page (and any associated centroid vector page), and updates the result
/// counter.
#[allow(clippy::too_many_arguments)]
fn free_node_and_descendants(
    id_hash: u64,
    mmap: &mut MmapMut,
    header: &mut FileHeader,
    btree: &mut BTreeIndex,
    sparse_index: &mut SparseIndex,
    l2_meta: &mut L2MetaIndex,
    file: &mut File,
    result: &mut MergeCompressResult,
) -> Result<(), MemHopError> {
    let page_ref = match btree.search(id_hash) {
        Some(pr) => pr,
        None => return Ok(()),
    };
    let page_id = crate::shared::slot_io::decode_page_id(page_ref);

    // Load node to traverse children and free the centroid vector page
    let ctx = {
        let slot_data = match crate::shared::slot_io::get_slot_data(&mmap[..], page_ref) {
            Some(d) => d,
            None => return Ok(()),
        };
        match ContextSlot::deserialize(slot_data) {
            Ok(c) => c,
            Err(_) => return Ok(()),
        }
    };

    // Recursively free children first (post-order traversal)
    let child_ids = ctx.children_ids.clone();
    for &child_id in &child_ids {
        free_node_and_descendants(
            child_id,
            mmap,
            header,
            btree,
            sparse_index,
            l2_meta,
            file,
            result,
        )?;
    }

    // Free centroid vector page if present
    if ctx.centroid_page_ref != 0 {
        let v_page_id = crate::shared::slot_io::decode_page_id(ctx.centroid_page_ref);
        if v_page_id > 0 {
            let v_offset = (v_page_id as usize) * PAGE_SIZE;
            if v_offset + PAGE_SIZE <= mmap.len() {
                mmap[v_offset..v_offset + PAGE_SIZE].fill(0);
                let _ = free_page(mmap, header, v_page_id);
            }
        }
    }

    // Remove from indices
    btree.remove(id_hash);
    sparse_index.remove_document(id_hash);
    l2_meta.remove(id_hash);

    // Zero and free the page
    let page_offset = crate::shared::slot_io::page_offset(page_id);
    let page_end = page_offset + PAGE_SIZE;
    if page_end <= mmap.len() {
        mmap[page_offset..page_end].fill(0);
    }
    free_page(mmap, header, page_id)?;

    result.nodes_removed += 1;

    let _ = file; // keep signature symmetric with other helpers
    Ok(())
}
